name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar SVG do Snake
        uses: Platane/snk@master
        with:
          github_user_name: polarStrxt
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy para GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Atualizando Snake SVG automático"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
